#!/usr/bin/env python3
"""
Scout Phase 1: Daily Intelligence Briefing

Summarizes ingested signals, scored velocities, and routing.

Usage:
  python3 scripts/scout_daily_analysis.py

Schedule:
  Daily via cron: 03:00 UTC (after routing at 02:45)
"""

import json
import os
from datetime import datetime
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(levelname)s - %(message)s',
    handlers=[
        logging.FileHandler('logs/scout_analysis.log'),
        logging.StreamHandler()
    ]
)
logger = logging.getLogger(__name__)

def create_daily_briefing():
    """Create daily intelligence briefing."""
    
    today = datetime.utcnow().strftime("%Y-%m-%d")
    
    briefing = {
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "date": today,
        "summary": "Scout Phase 1 Daily Intelligence Briefing",
        "signals_ingested": 0,
        "signals_scored": 0,
        "critical_velocity": 0,
        "high_velocity": 0,
        "routing_summary": {},
        "status": "Phase 1: Ready for Phase 2 API integration"
    }
    
    # Load processed signals
    proc_dir = f"data/scout/processed-signals/{today}"
    if os.path.exists(proc_dir):
        scored_file = os.path.join(proc_dir, "scored-signals.json")
        if os.path.exists(scored_file):
            with open(scored_file) as f:
                scored = json.load(f)
                briefing["signals_scored"] = scored.get("summary", {}).get("total_signals", 0)
                briefing["critical_velocity"] = scored.get("summary", {}).get("critical_count", 0)
                briefing["high_velocity"] = scored.get("summary", {}).get("high_count", 0)
        
        routed_file = os.path.join(proc_dir, "routed-signals.json")
        if os.path.exists(routed_file):
            with open(routed_file) as f:
                routed = json.load(f)
                briefing["routing_summary"] = routed.get("routing_summary", {})
    
    # Write markdown briefing
    brief_dir = f"memory/scout-analysis"
    os.makedirs(brief_dir, exist_ok=True)
    
    filename = os.path.join(brief_dir, f"{today}-scout-briefing.md")
    
    try:
        with open(filename, 'w') as f:
            f.write(f"# Scout Daily Intelligence Briefing — {today}\n\n")
            f.write(f"**Generated:** {briefing['timestamp']}\n\n")
            
            f.write(f"## Summary\n\n")
            f.write(f"- Status: {briefing['status']}\n")
            f.write(f"- Signals ingested: {briefing['signals_ingested']}\n")
            f.write(f"- Signals scored: {briefing['signals_scored']}\n")
            f.write(f"- CRITICAL velocity signals: {briefing['critical_velocity']}\n")
            f.write(f"- HIGH velocity signals: {briefing['high_velocity']}\n\n")
            
            if briefing["routing_summary"]:
                f.write(f"## Routing Summary\n\n")
                for dest, count in briefing["routing_summary"].items():
                    if count > 0:
                        agent = dest.replace("routed_to_", "").upper()
                        f.write(f"- {agent}: {count} signal(s)\n")
                f.write(f"\n")
            
            f.write(f"## Phase 1 Status\n\n")
            f.write(f"Scout Phase 1 MVP is operational:\n")
            f.write(f"- ✅ Signal ingestion structure ready\n")
            f.write(f"- ✅ Velocity scoring algorithm implemented\n")
            f.write(f"- ✅ Signal routing framework active\n")
            f.write(f"- ⏳ Phase 2: Real API integrations pending\n\n")
            
            f.write(f"## Next Steps\n\n")
            f.write(f"Phase 2 (Week 2):\n")
            f.write(f"- Twitter Streaming API integration\n")
            f.write(f"- GitHub release tracking\n")
            f.write(f"- Discord webhook monitoring\n")
            f.write(f"- Firecrawl web content ingestion\n")
            f.write(f"- Real narrative heatmaps\n")
            f.write(f"- Crypto regime classification\n")
            f.write(f"- AI launch radar\n\n")
            
            f.write(f"---\n")
            f.write(f"*Report generated by Scout at {briefing['timestamp']}*\n")
        
        logger.info(f"Briefing written: {filename}")
        
        # Write JSON output too
        json_file = os.path.join(brief_dir, f"{today}-scout-briefing.json")
        with open(json_file, 'w') as f:
            json.dump(briefing, f, indent=2)
        logger.info(f"JSON briefing written: {json_file}")
        
        return True
    except Exception as e:
        logger.error(f"Briefing creation failed: {e}")
        return False

if __name__ == "__main__":
    success = create_daily_briefing()
    exit(0 if success else 1)
